### ISSUE TITLE
The state of redux-autoform-material-ui

### ISSUE THREAD

**Issue by andrerpena** [redux-autoform/redux-autoform-material-ui#28]
Please, update this thread with the state of this repo. Is it working already? Plans?

**Comment by JonatanSalas** [comment]
Actually the only I have are the groups and checkbox, I'm trying to fix the demo to test this components, and I want to keep it working with the rest.

**Comment by andrerpena** [comment]
Ok, thanks. No problem. Let's update this thread as we go further.

**Comment by JonatanSalas** [comment]
Okey, I will keep this open and when getting advance I will reference this issue. :smile:

**Comment by JonatanSalas** [comment]
@andrerpena I'm currently working on setting up the demo in order to keep the component migration and test their behaviour. I have good news about styles. The latest versions of Material-UI have introduced the className props to all it's components, so you will be able to style them. What I want to do, it's to mark all the components with css class names, so the final users can override the css and easily style the components in the way they want.

**Comment by JonatanSalas** [comment]
@andrerpena @danigomez I'm fixing the demo, now some basic components are working: 
- TextBox
- TextArea
- Email
- Password
- WizardGroup
- TabGroup

But some of them require a bit of work to emulate properly part of the functionality offered by bootstrap. So I will keep working on them. 

The demo really looks awful, but it will be good with a lof of work I will be putting on.

**Comment by andrerpena** [comment]
@JonatanSalas this is really really good news! Congratulations!

**Comment by andrerpena** [comment]
Is the demo published already? Or do I have to download the repo?

**Comment by JonatanSalas** [comment]
@andrerpena You have to download the repo for now. Because I don't have all components implemented.

**Comment by andrerpena** [comment]
Ok.. I'll do it when get home. Great

**Comment by JonatanSalas** [comment]
This is how it actually looks

![captura de pantalla de 2016-08-30 16 05 34](https://cloud.githubusercontent.com/assets/7697196/18103097/9c12e0bc-6ecb-11e6-8767-51bcb03db745.png)

**Comment by JonatanSalas** [comment]
After final fixes

![captura de pantalla de 2016-08-30 17 40 50](https://cloud.githubusercontent.com/assets/7697196/18106191/fb506362-6ed8-11e6-8ebc-47c078f582ea.png)

**Comment by andrerpena** [comment]
Please... Add paddings to the form. If you do it it will be amazing. =)))

Em 30 de ago de 2016 5:41 PM, "Jonatan E. Salas" notifications@github.com
escreveu:

**Comment by andrerpena** [comment]
@JonatanSalas Congrats by the way. Awesome job. (just please add paddings)

**Comment by JonatanSalas** [comment]
it's a work in progress maaaaaaan jajajaja

**Comment by andrerpena** [comment]
hauhau sorry. Good progress though.

**Comment by JonatanSalas** [comment]
jajaja no trouble! We are on the way

**Comment by JonatanSalas** [comment]
@andrerpena fixed! 

![material-ui](https://cloud.githubusercontent.com/assets/7697196/18113000/be31864e-6f02-11e6-960e-05a16b246827.png)

**Comment by JonatanSalas** [comment]
@andrerpena @danigomez this is the status:
- TextBox
- TextArea
- Email
- Password
- WizardGroup
- TabGroup
- CheckBox
- Radio

**Comment by andrerpena** [comment]
Getting better.. Except that I'd add more padding to the top. But this is getting really beautiful

**Comment by andrerpena** [comment]
About the components, you're getting there. Congrats dude!

**Comment by JonatanSalas** [comment]
ok! We will add that padding

**Comment by andrerpena** [comment]
Great.. by the way, I prefer the option in which the top bar (update, inline.. stacked..) has gray buttons instead of blue buttons. I think it's prettier, but that's just my opinion :)

**Comment by JonatanSalas** [comment]
It has grey buttons now!

**Comment by JonatanSalas** [comment]
With Top padding and grey buttons! 

![captura de pantalla de 2016-08-31 14 58 32](https://cloud.githubusercontent.com/assets/7697196/18140341/784279fc-6f8b-11e6-930e-9b00e9ccbbbe.png)

**Comment by andrerpena** [comment]
Beautiful!

**Comment by JonatanSalas** [comment]
@andrerpena @danigomez this is the current status: 
- TextBox
- Number
- TextArea
- Email
- Password
- WizardGroup
- WizardTabGroup
- TabGroup
- CheckBox
- Radio

I have refactored the demo because I was needing a more organized folder structure. I have to keep on adding more functionallity to this components in order to emulate the features of bootstrap-ui.

**Comment by JonatanSalas** [comment]
Guys, the demo is published now with the components I current have here: https://redux-autoform.github.io/redux-autoform-material-ui/

**Comment by andrerpena** [comment]
First. Amazing job. Congrats. Really good work. Some thoughts:
1. The presets should be rebuilt to reflect Material. Maybe, for instance, `addonBefore` and `addonAfter` should be removed from TextBox just because that's not how Material works. The presets should be refactored.
2. Once you consider it to be in a "presentable" state, we should update the RAF's readme.md file to link to this demo (if you didn't already). The same for the RAF-MUI one.

**Comment by JonatanSalas** [comment]
@andrerpena when you can, could you look at the presets and modify them :smile:? 

This is the current status: 
- TextBox
- Number
- TextArea
- Email
- Password
- Group
- WizardGroup
- WizardTabGroup
- TabGroup
- CheckBox
- Radio
- Select

This days I will be working on the last components that are the following ones: 
- FieldGroup
- LookUp
- DatePicker/TimePicker (This one should be separated, I suppose)
- FileUpload
- Static

And at last add tests with enzyme.

**Comment by JonatanSalas** [comment]
@andrerpena @danigomez We are able to release a beta version! 
- TextBox
- Number
- TextArea
- Email
- Password
- Group
- WizardGroup
- WizardTabGroup
- TabGroup
- CheckBox
- Radio
- Select
- FieldGroup
- LookUp (This has a small bug that I will solve)
- DatePicker/TimePicker (This one support date and time, but not datetime, I have to work on this one)
- FileUpload

The only that rest: 
- Static

The demo is currently up to date, so you can play with the components that we currently have! :smile: Let me know when you find something!

@andrerpena you can start to link the Demo in **readme.md**

**Comment by JonatanSalas** [comment]
I have added support for Questionnaire Forms. Then I will add Support for Wizard with Stepper. Added component: 
- QuestionnaireGroup

**Comment by JonatanSalas** [comment]
@danigomez I will do some refactors in **Wizard/WizardTabGroup/TabGroup**. I don't like the way that we use to update the context of this Groups, we should handle this in the componentWillReceiveProps callback, as I'm doing now on QuestionnaireGroup and I think that we should use the Context API from React.

**Comment by danigomez** [comment]
I don't know if is the same thing, that callback is not called at first
render and the context will be empty

**Comment by JonatanSalas** [comment]
I'm using componentDidMount and componentWillReceiveProps, the first one to setup previously to the initial render, and the second one, to setup the rest of the time that some prop change.

**Comment by JonatanSalas** [comment]
The new state of this is that I have released a version 1.0.0 of the library to start testing with redux-autoform. 

I have finally fixed the bug with Lookup component, and added the Static one. I have started to add some basic tests with enzyme, I will keep working on them.
