### ISSUE TITLE
cannot resolve EditComponentFactory and DetailsComponentFactory

### ISSUE THREAD

**Issue by anatolicvs** [redux-autoform/redux-autoform-material-ui#317]
this package can not resolve when I called the these factory methods ''EditComponentFactory" and ''DetailsComponentFactory" on my side project..But I download your code from github directly and run it, your bundled demos are working well with unproduction version your project  on my machine locally.

my npm version is : 5.4.2
my node version is: 8.8.1
my OS: Sierra 10.12.6 (16G1212)

Please, Can you release new version? 

Also, it's really cool job, well done.

**Comment by anatolicvs** [comment]
the problem caused by prop-types lib, it has been change with react v16.0. 
then simply I changed GroupPropTypes.js like these, 
   var _propTypes = require('prop-types');
exports.default = {
    component: _propTypes.PropTypes.string,
    fields: _propTypes.PropTypes.array.isRequired,
    layout: _propTypes.PropTypes.object.isRequired,
    componentFactory: _propTypes.PropTypes.object.isRequired
};

the problem I have got, it solved.

**Comment by JonatanSalas** [comment]
@aytacozkan hey! Thanks for pointing where's the bug! I'll try to solve and release a newer version 😄

**Comment by JonatanSalas** [comment]
@aytacozkan I have fixed the prop-types imports and also, released a new version 1.1.11-experimental. Would you mind to test it?

**Comment by anatolicvs** [comment]
it's awsome @JonatanSalas !! :) thank you.

**Comment by JonatanSalas** [comment]
You're welcome! Thanks for debugging the issue!
