### ISSUE TITLE
Create Number component

### ISSUE THREAD

**Issue by JonatanSalas** [redux-autoform/redux-autoform-material-ui#38]

**Comment by andrerpena** [comment]
Are we creating components specifically for each type? I mean.. It's not that I'm opposed to it, it's just that that's not the way the BS UI is. You see, I'm using the TextBox component for numbers. Maybe we should have separate components. I don't know.

**Comment by JonatanSalas** [comment]
Numbers with min and max! That's this component. In bootstrap there's no support for a Number component that you can set min and max values.

**Comment by andrerpena** [comment]
Yes it makes sense..
