### ISSUE TITLE
Issue with localizer

### ISSUE THREAD

**Issue by JonatanSalas** [redux-autoform/redux-autoform-material-ui#41]
I'm currently having this issue guys @andrerpena @danigomez. Do you have any idea what could be?

![captura de pantalla de 2016-09-04 19-09-03](https://cloud.githubusercontent.com/assets/7697196/18234219/49663312-72d3-11e6-9936-b7fdd72fd8cc.png)

**Comment by danigomez** [comment]
Check that material project and Autoform project are using the same autoform utils version !

**Comment by JonatanSalas** [comment]
Okey, I will take a look at it! Thank you @danigomez  :smile:

**Comment by JonatanSalas** [comment]
I'm using Autoform experimental and utils experimental:

``` json
"redux-autoform-utils": "^1.0.4-experimental"
"redux-autoform": "^0.10.5-experimental"
```

They are supposed to use the same version of localizers.. :disappointed:

**Comment by JonatanSalas** [comment]
@danigomez I think that I know why is the error, the trouble it's that I'm setting only the numbroLocalizer and I'm not setting the dateLocalizer.

**Comment by andrerpena** [comment]
Check lines 22 and 25 from the `client.js` file from the BS UI: https://github.com/redux-autoform/redux-autoform-bootstrap-ui/blob/master/demo/Client.js#L22

Localizers should be set for both Moment and Numbro.

**Comment by JonatanSalas** [comment]
Cool. I will set both in the demo so I fix this error! :smile: Thanks!
