### ISSUE TITLE
Create DateTimePicker component

### ISSUE THREAD

**Issue by JonatanSalas** [redux-autoform/redux-autoform-material-ui#5]

**Comment by JonatanSalas** [comment]
The problem here will be the datetime type because currently Date and Time picker in MaterialUI are different components. 

I will work with date and time only, after that see how I can implement datetime part.

**Comment by andrerpena** [comment]
BS and MUI don't have to be 100% feature compatible. If you don't have a DateTimePicker with both Date and Time, than don't worry. Just throw an exception. Don't fail silently.

**Comment by JonatanSalas** [comment]
Okey.. but we should workaround over this u.u

**Comment by JonatanSalas** [comment]
I think to see the core of the Material UI and extract Date/Time pickers code and see how to merge into one

**Comment by andrerpena** [comment]
That would be the ideal solution :smile:
