### ISSUE TITLE
Implement the EntityContainer component

### ISSUE THREAD

**Issue by andrerpena** [redux-autoform/redux-autoform-material-ui#54]
Like this: https://github.com/redux-autoform/redux-autoform-bootstrap-ui/blob/master/src/components/field/EntityContainer.js

I'm sorry I didn't use the ES2015 syntax.. I'll fix it :cry:

**Comment by JonatanSalas** [comment]
No trouble, I will look at it today!

**Comment by JonatanSalas** [comment]
@andrerpena This is supported now! Yay! 😄
